name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Icons
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          base: ""
          filename: metrics.plugin.topics.icons.svg
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
